bind_address = "0.0.0.0:25565"
motd = "Minecraft High Performance Redstone Server"
chat_format = "<{username}><{username}><{username}><{username}> {message}"
max_players = 99999
view_distance = 8
bungeecord = false
whitelist = false
schemati = false
block_in_hitbox = true
auto_redpiler = false
